apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-github-base
  namespace: tekton-ci
spec:
  params:
  - name: buildUUID
    value: $(header.X-GitHub-Delivery)
  - name: package
    value: $(body.repository.full_name)
  - name: gitRepository
    value: $(body.repository.html_url)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-clone-depth
  namespace: tekton-ci
spec:
  params:
  - name: gitCloneDepth
    value: $(extensions.git_clone_depth)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-webhook-pull-request
  namespace: tekton-ci
spec:
  params:
  - name: gitRevision
    value: $(body.pull_request.head.sha)
  - name: pullRequestNumber
    value: $(body.pull_request.number)
  - name: pullRequestUrl
    value: $(body.pull_request.html_url)
  - name: pullRequestBaseRef
    value: $(body.pull_request.base.ref)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-webhook-comment
  namespace: tekton-ci
spec:
  params:
  - name: gitRevision
    value: $(body.extensions.add_pr_body.pull_request_body.head.sha)
  - name: pullRequestNumber
    value: $(body.extensions.add_pr_body.pull_request_body.number)
  - name: pullRequestUrl
    value: $(body.issue.pull_request.html_url)
  - name: pullRequestBaseRef
    value: $(body.extensions.add_pr_body.pull_request_body.base.ref)
  - name: gitHubCommand
    value: $(body.comment.body)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-webhook-tektoncd-comment
  namespace: tekton-ci
spec:
  params:
  - name: gitHubCommand
    value: $(body.comment.body)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-webhook-pr-labels
  namespace: tekton-ci
spec:
  params:
  - name: labels
    value: $(body.pull_request.labels)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-webhook-issue-labels
  namespace: tekton-ci
spec:
  params:
  - name: labels
    value: $(body.issue.labels)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-webhook-pr-body
  namespace: tektonci
spec:
  params:
    - name: body
      value: $(body.pull_request.body)
