apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-doc-reviews
spec:
  params:
  - name: buildUUID
    description: UUID used to track a CI Pipeline Run in logs
  - name: package
    description: org/repo
  - name: pullRequestNumber
    description: The pullRequestNumber
  - name: pullRequestUrl
    description: The HTML URL for the pull request
  - name: pullRequestBaseRef
    description: |
      The base git ref for the pull request. This is the branch the
      pull request would merge onto once approved.
  - name: gitRepository
    description: The git repository that hosts context and Dockerfile
  - name: gitRevision
    description: The Git revision to be used.
  - name: gitCloneDepth
    description: Number of commits in the change + 1
  - name: gitHubCommand
    description: |
      The GitHub command that was used a trigger. This is only available when
      this template is triggered by a comment. The default value is for the
      case of a pull_request event.
    default: ""
  - name: labels
    description: List of labels currently on the Pull Request
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: request-pr-docs-reviewer-
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
      annotations:
        tekton.dev/gitRevision: "$(tt.params.gitRevision)"
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
    spec:
      serviceAccountName: tekton-ci-jobs
      timeout: 10m
      workspaces:
        - name: sources
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: github
          secret:
            secretName: "bot-token-github"
      pipelineRef:
        name: request-pr-docs-reviewer
      params:
        - name: pullRequestNumber
          value: $(tt.params.pullRequestNumber)
        - name: pullRequestBaseRef
          value: $(tt.params.pullRequestBaseRef)
        - name: gitRepository
          value: "$(tt.params.gitRepository)"
        - name: gitCloneDepth
          value: $(tt.params.gitCloneDepth)
        - name: fileFilterRegex
          # Start with docs, ends with .md or *.rst, but not in vendor/ or thirdparty/
          value: "(^docs\\/.*|^(?!vendor\\/)(?!thirdparty\\/).*\\.(md|rst)$)"
        - name: package
          value: $(tt.params.package)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: label-check
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
spec:
  params:
  - name: buildUUID
    description: UUID used to track a CI Pipeline Run in logs
  - name: package
    description: org/repo
  - name: pullRequestNumber
    description: The pullRequestNumber
  - name: pullRequestUrl
    description: The HTML URL for the pull request
  - name: gitRepository
    description: The git repository that hosts context and Dockerfile
  - name: gitRevision
    description: The Git revision to be used.
  - name: gitCloneDepth
    description: Number of commits in the change + 1
  - name: gitHubCommand
    description: |
      The GitHub command that was used a trigger. This is only available when
      this template is triggered by a comment. The default value is for the
      case of a pull_request event.
    default: ""
  - name: labels
    description: List of labels currently on the Pull Request
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: check-pr-labels-
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/check-name: check-pr-has-kind-label
        tekton.dev/kind: ci
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
      annotations:
        tekton.dev/gitRevision: "$(tt.params.gitRevision)"
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
    spec:
      pipelineRef:
        name: tekton-kind-label
      params:
        - name: labels
          value: $(tt.params.labels)
        - name: checkName
          value: check-pr-has-kind-label
        - name: gitHubCommand
          value: $(tt.params.gitHubCommand)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: check-github-tasks-completed
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
spec:
  params:
  - name: buildUUID
    description: UUID used to track a CI Pipeline Run in logs
  - name: package
    description: org/repo
  - name: pullRequestNumber
    description: The pullRequestNumber
  - name: pullRequestUrl
    description: The HTML URL for the pull request
  - name: gitRepository
    description: The git repository that hosts context and Dockerfile
  - name: gitRevision
    description: The Git revision to be used.
  - name: gitCloneDepth
    description: Number of commits in the change + 1
  - name: gitHubCommand
    description: |
      The GitHub command that was used a trigger. This is only available when
      this template is triggered by a comment. The default value is for the
      case of a pull_request event.
    default: ""
  - name: body
    description: The body of the Pull Request
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: check-github-tasks-completed-
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/check-name: check-github-tasks-completed
        tekton.dev/kind: ci
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
      annotations:
        tekton.dev/gitRevision: "$(tt.params.gitRevision)"
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
    spec:
      pipelineRef:
        name: tekton-github-tasks-completed
      params:
        - name: body
          value: $(tt.params.body)
        - name: checkName
          value: check-github-tasks-completed
        - name: gitHubCommand
          value: $(tt.params.gitHubCommand)
